development:
  adapter: mysql2
  database: ti_tender_remote
  username: root
  password: 1q2w3e4r
  encoding: utf8
  host: localhost
  port: 3306
  reconnect: true
  pool: 5

production:
  adapter: mysql2
  database: ti_tender_remote
  username: root
  password: 1q2w3e4r
  encoding: utf8
  host: localhost
  port: 3306
  reconnect: true
  pool: 5
